
# SYNOPSIS:
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

#   HEADERS = DomainDatabase.hh DbtestDomainObjects.hh DataTypes.hpp Containers.hpp TcpUtils.hpp SocketStreamerBase.hh MemoryFence.h ux_selector.hpp gx_ipc.h
CC = g++ -Ilibinclude

CPPFLAGS = -c -std=c++11 -g -Wall -Wextra -fvisibility=hidden
LDFLAGS= -Llib -lgtest -lpthread

LIB = libphoenix.a
LIB_SOURCES = TcpUtils.cpp SocketStreamerBase.cpp ux_selector.cpp gx_ipc.cpp Logger.cpp GlobalUtils.cpp ReliableMulticastChannel.cpp stats.cpp jsonxx.cpp
LIB_OBJECTS = $(LIB_SOURCES:.cpp=.o)

SOURCES = DiskWritersTest.cpp JsonTest.cpp DBTest.cpp DBMirrorTest.cpp SockTest.cpp testmain.cpp jsonxx_test.cpp ProducerConsumerQueueTest.cpp thread_pool_test.cpp
OBJECTS=$(SOURCES:.cpp=.o)

EXECUTABLE=testmain

all: $(EXECUTABLE)

#######for libobj in $(LIB_OBJECTS); do ar -rcvs ${LIB} out/$$libobj; done ###
$(EXECUTABLE): $(LIB) $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) $(LIB) -o $@  -lm

$(LIB) : $(LIB_OBJECTS)
	- ar -rcvs ${LIB} $(LIB_OBJECTS)
	- ranlib ${LIB}

.cpp.o:
	$(CC) $(CPPFLAGS) -o $@ $<

clean:
	rm -f $(LIB) $(LIB_OBJECTS) $(OBJECTS) ${EXECUTABLE}
